### ISSUE TITLE
可以更新下代码，适配 spring-boot 和 spring-security-oauth2 吗

### ISSUE THREAD

**Issue by kukat** [HQIT/tech-talk-spring-oauth2-wechat-mp#1]

**Comment by SUGE2016** [comment]
- 这个例子是去年team tech talk的一个demo工程，没有计划会去更新（除非又要talking并且依赖的技术有本质的更新）
- 这个例子里面用到的就是spring-boot和spring-security-oauth2，或者你可以看看其他例子，比如这个：https://github.com/HQIT/tech-talk-spring-oauth2-jwt-zuul-ui-example

**Comment by kukat** [comment]
是我的描述有误，是 spring boot 2 的适配问题。非 java 栈，还在学习 spring/spring boot 😄

**Comment by SUGE2016** [comment]
- java 8作为baseline会有很多兼容性问题，我们目前不会迁移到生成过程中。
- 你加油！
